#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x7A1C87E3F5BC42A8 (davidism@gmail.com)
#
Name     : click
Version  : 7.0
Release  : 16
URL      : https://files.pythonhosted.org/packages/f8/5c/f60e9d8a1e77005f664b76ff8aeaee5bc05d0a91798afd7f53fc998dbc47/Click-7.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/f8/5c/f60e9d8a1e77005f664b76ff8aeaee5bc05d0a91798afd7f53fc998dbc47/Click-7.0.tar.gz
Source99 : https://files.pythonhosted.org/packages/f8/5c/f60e9d8a1e77005f664b76ff8aeaee5bc05d0a91798afd7f53fc998dbc47/Click-7.0.tar.gz.asc
Summary  : Composable command line interface toolkit
Group    : Development/Tools
License  : BSD-3-Clause
Requires: click-python3
Requires: click-license
Requires: click-python
Requires: click
Requires: colorama
BuildRequires : buildreq-distutils3
BuildRequires : colorama
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : tox
BuildRequires : virtualenv

%description
==========
        
        Click is a Python package for creating beautiful command line interfaces
        in a composable way with as little code as necessary. It's the "Command
        Line Interface Creation Kit". It's highly configurable but comes with
        sensible defaults out of the box.
        
        It aims to make the process of writing command line tools quick and fun
        while also preventing any frustration caused by the inability to
        implement an intended CLI API.

%package license
Summary: license components for the click package.
Group: Default

%description license
license components for the click package.


%package python
Summary: python components for the click package.
Group: Default
Requires: click-python3 = %{version}-%{release}

%description python
python components for the click package.


%package python3
Summary: python3 components for the click package.
Group: Default
Requires: python3-core

%description python3
python3 components for the click package.


%prep
%setup -q -n Click-7.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1537930129
python3 setup.py build

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/click
cp LICENSE.rst %{buildroot}/usr/share/doc/click/LICENSE.rst
cp docs/license.rst %{buildroot}/usr/share/doc/click/docs_license.rst
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/doc/click/LICENSE.rst
/usr/share/doc/click/docs_license.rst

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
