#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x7A1C87E3F5BC42A8 (davidism@gmail.com)
#
Name     : click
Version  : 7.1.2
Release  : 27
URL      : https://files.pythonhosted.org/packages/27/6f/be940c8b1f1d69daceeb0032fee6c34d7bd70e3e649ccac0951500b4720e/click-7.1.2.tar.gz
Source0  : https://files.pythonhosted.org/packages/27/6f/be940c8b1f1d69daceeb0032fee6c34d7bd70e3e649ccac0951500b4720e/click-7.1.2.tar.gz
Source1  : https://files.pythonhosted.org/packages/27/6f/be940c8b1f1d69daceeb0032fee6c34d7bd70e3e649ccac0951500b4720e/click-7.1.2.tar.gz.asc
Summary  : Composable command line interface toolkit
Group    : Development/Tools
License  : BSD-3-Clause
Requires: click-license = %{version}-%{release}
Requires: click-python = %{version}-%{release}
Requires: click-python3 = %{version}-%{release}
Requires: Pillow
Requires: click
Requires: colorama
BuildRequires : Pillow
BuildRequires : buildreq-distutils3
BuildRequires : click
BuildRequires : colorama
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : tox
BuildRequires : virtualenv

%description
==========
        
        Click is a Python package for creating beautiful command line interfaces
        in a composable way with as little code as necessary. It's the "Command
        Line Interface Creation Kit". It's highly configurable but comes with
        sensible defaults out of the box.
        
        It aims to make the process of writing command line tools quick and fun
        while also preventing any frustration caused by the inability to
        implement an intended CLI API.

%package license
Summary: license components for the click package.
Group: Default

%description license
license components for the click package.


%package python
Summary: python components for the click package.
Group: Default
Requires: click-python3 = %{version}-%{release}

%description python
python components for the click package.


%package python3
Summary: python3 components for the click package.
Group: Default
Requires: python3-core
Provides: pypi(click)

%description python3
python3 components for the click package.


%prep
%setup -q -n click-7.1.2
cd %{_builddir}/click-7.1.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1608003656
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/click
cp %{_builddir}/click-7.1.2/LICENSE.rst %{buildroot}/usr/share/package-licenses/click/6fb11e02ffe0f79b74f1c6034b4ae6e7717a69f8
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/click/6fb11e02ffe0f79b74f1c6034b4ae6e7717a69f8

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
